/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package feed.noticias.controller;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.annotation.WebServlet;

import feed.noticias.resources.UsuarioBuilder;
import feed.noticias.model.Usuario;
import feed.noticias.model.UsuarioDAO;

@WebServlet(urlPatterns={"/cadastro"})
public class Cadastro extends HttpServlet {	
	/**
	 *
	 */
	private static final long serialVersionUID = 8818607052067640463L;

	@Override
	public void doGet(HttpServletRequest req,HttpServletResponse res) {
		try{
			req.getRequestDispatcher("/WEB-INF/cadastro.jsp").forward(req, res);
		} catch (Exception e){
			System.out.println("Erro em IO ou no Servlet");
		}
	}
	
	@Override
	protected void doPost(HttpServletRequest req, HttpServletResponse resp){
		try {
			String nome = req.getParameter("nome");
			String email = req.getParameter("email");
			String senha = req.getParameter("senha");

			UsuarioBuilder uBuilder = new UsuarioBuilder().iniciar().comNome(nome).comEmail(email).comSenha(senha).ehAdmin(false);
			Usuario usuario = uBuilder.criarUsuario();
			UsuarioDAO.getInstance().persist(usuario);

			req.getRequestDispatcher("/WEB-INF/feed.jsp");
		} catch (Exception e) {
			System.out.println("Erro em IO ou no Servlet");
		}
	}
}
