/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package feed.noticias.controller;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.servlet.annotation.WebServlet;

import feed.noticias.model.NoticiaDAO;
import feed.noticias.model.Noticia;

@WebServlet(urlPatterns={"/noticia"})
public class NoticiaController extends HttpServlet {	
	private static final long serialVersionUID = 8818607052067640463L;

	@Override
	public void doGet(HttpServletRequest req,HttpServletResponse res) {
		
		Long id  = Long.parseLong(req.getParameter("id"));
		HttpSession session= req.getSession();
		
		Noticia noticia = NoticiaDAO.getInstance().find(id);

		req.setAttribute("titulo", noticia.getTitulo());


		if (session.getAttribute("uname") != null) {
			req.setAttribute("corpo", noticia.getCorpo());
		}

		try{
			req.getRequestDispatcher("/WEB-INF/noticia.jsp").forward(req, res);
		} catch (Exception e){
			System.out.println("Erro em IO ou no Servlet");
		}
	}

	@Override
	protected void doDelete(HttpServletRequest req, HttpServletResponse resp) {
		try {
			Long id = Long.parseLong(req.getParameter("id"));
			if (id > 0) {
				NoticiaDAO.getInstance().removeById(id);
			}
		} catch (Exception e) {
			System.out.println("Erro em IO ou no Servlet");
		}
	
	}
}
