/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package feed.noticias.controller;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.annotation.WebServlet;

import feed.noticias.model.UsuarioDAO;

@WebServlet(urlPatterns={"/usuario"})
public class UsuarioController extends HttpServlet {	
	/**
	 *
	 */
	private static final long serialVersionUID = 8818607052067640463L;

	@Override
	public void doGet(HttpServletRequest req,HttpServletResponse res) {
		try{
			req.getRequestDispatcher("/WEB-INF/usuario.jsp").forward(req, res);
		} catch (Exception e){
			System.out.println("Erro em IO ou no Servlet");
		}
	}
	
	@Override
	protected void doDelete(HttpServletRequest req, HttpServletResponse resp) {
		try {
			Long id  = Long.parseLong(req.getParameter("id"));
			if (id > 0) {
				UsuarioDAO.getInstance().removeById(id);
			}
		} catch (Exception e) {
			System.out.println("Erro em IO ou no Servlet");
		}
	}
}
